{
  pkgs,
  inputs,
  config,
  ...
}:
let
  endpoint = "127.0.0.1:8080";
  cacheName = "h2";
in
{
  imports = [ ./secrets/secret.nix ];
  services.atticd = {
    enable = true;

    environmentFile = config.age.secrets.attic-env.path;

    settings = {
      listen = endpoint;

      jwt = { };

      # storage = {
      #   type = "local";
      #   path = "/srv/attic";
      # };

      chunking = {
        # The minimum NAR size to trigger chunking
        #
        # If 0, chunking is disabled entirely for newly-uploaded NARs.
        # If 1, all NARs are chunked.
        nar-size-threshold = 64 * 1024; # 64 KiB

        # The preferred minimum size of a chunk, in bytes
        min-size = 16 * 1024; # 16 KiB

        # The preferred average size of a chunk, in bytes
        avg-size = 64 * 1024; # 64 KiB

        # The preferred maximum size of a chunk, in bytes
        max-size = 256 * 1024; # 256 KiB
      };
    };
  };

  systemd.services.attic-cache-init = {
    description = "Initialize Attic cache";

    wantedBy = [ "multi-user.target" ];

    after = [ "atticd.service" ];
    wants = [ "atticd.service" ];

    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };

    path = [
      pkgs.coreutils
      pkgs.curl
      inputs.attic.packages.${pkgs.system}.attic-client
    ];

    script = ''
      set -eu

      endpoint="http://${endpoint}"

      # just to be sure poll for attic's availability even if this unit already requires atticd's
      until ${pkgs.curl}/bin/curl -fsS "$endpoint/" >/dev/null; do
        sleep 1
      done

      # source the env file as an export for the token subprocess
      set -a
      source ${config.age.secrets.attic-env.path}      
      set +a

      token="$(
        ${config.services.atticd.package}/bin/atticadm \
          -f ${config.services.atticd.configFile} \
          make-token \
          --sub bootstrap \
          --validity "10m" \
          --create-cache "${cacheName}" \
      )"

      # to avoid polluting env with autogenerated config
      export TMP_HOME="$(mktemp -d)"
      export XDG_CONFIG_HOME="$TMP_HOME/config"
      mkdir -p "$XDG_CONFIG_HOME"
      trap 'rm -rf "$TMP_HOME"' EXIT

      ${pkgs.attic-client}/bin/attic \
        login local "$endpoint" "$token"

      # idempotency invariant
      if ! ${pkgs.attic-client}/bin/attic \
          cache info "local:${cacheName}" >/dev/null 2>&1
      then
        ${pkgs.attic-client}/bin/attic \
          cache create "local:${cacheName}" \
          --public
      fi
    '';
  };
}
