# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6c6e6be0-03b4-45fb-988a-d29fe0bbae95";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/405bb33f-4ad0-4101-8ccf-670cde5b7f35"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
