name: deployment

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  toneriko-deploy:
    runs-on: ubuntu-latest
    environment: toneriko
    steps:
      - uses: actions/checkout@v7
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.TONERIKO_DEPLOYER_KEY }}
      - name: Configure SSH client
        env:
          SSH_KNOWN_HOSTS: ${{ vars.SSH_KNOWN_HOSTS }}
        run: |
          echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<'EOF'
          Host toneriko-deploy
            HostName toneriko.top
            User deployer
            ForwardAgent yes
            IdentityAgent $SSH_AUTH_SOCK
          EOF
          chmod 600 ~/.ssh/config
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        run: |
          nix run nixpkgs#nixos-rebuild -- \
            switch \
            --flake .#toneriko \
            --target-host toneriko-deploy \
            --sudo
